"""Generation task planner.

Converts a validated :class:`~engine.spec.schema.ApiSpec` into an ordered
list of :class:`GenerationTask` objects.  Each task describes one source
file to be generated by the LLM.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum

from engine.spec.schema import ApiSpec


class TaskKind(StrEnum):
    MODELS = "models"
    ROUTER = "router"
    MAIN = "main"
    TESTS = "tests"


@dataclass
class GenerationTask:
    """A single file-generation unit of work.

    Attributes
    ----------
    kind:
        High-level category of the file to generate.
    output_path:
        Relative path inside the generated project directory.
    prompt_builder:
        A zero-argument callable that returns the prompt string to send to
        the LLM.  It is built lazily so the spec object does not need to be
        serialised into the task.
    metadata:
        Arbitrary key/value metadata (e.g. model names, endpoint count).
    """

    kind: TaskKind
    output_path: str
    prompt_builder: object  # callable[[], str]
    metadata: dict = field(default_factory=dict)


def plan(spec: ApiSpec) -> list[GenerationTask]:
    """Return an ordered list of :class:`GenerationTask` for *spec*.

    The order is:

    1. ``models.py``  — data models (no deps)
    2. ``routers/api.py`` — router (depends on models)
    3. ``main.py`` — app entry-point (depends on router)
    4. ``tests/test_api.py`` — test suite (depends on all of the above)

    Parameters
    ----------
    spec:
        Validated DSL specification.

    Returns
    -------
    list[GenerationTask]
        Ordered generation tasks.
    """
    from engine.prompts.templates import (
        main_prompt,
        models_prompt,
        router_prompt,
        tests_prompt,
    )

    tasks: list[GenerationTask] = []

    if spec.models:
        tasks.append(
            GenerationTask(
                kind=TaskKind.MODELS,
                output_path="models.py",
                prompt_builder=lambda: models_prompt(spec),
                metadata={"model_count": len(spec.models)},
            )
        )

    if spec.endpoints:
        tasks.append(
            GenerationTask(
                kind=TaskKind.ROUTER,
                output_path="routers/api.py",
                prompt_builder=lambda: router_prompt(spec),
                metadata={"endpoint_count": len(spec.endpoints)},
            )
        )

    tasks.append(
        GenerationTask(
            kind=TaskKind.MAIN,
            output_path="main.py",
            prompt_builder=lambda: main_prompt(spec),
            metadata={"project_name": spec.name, "version": spec.version},
        )
    )

    if spec.endpoints:
        tasks.append(
            GenerationTask(
                kind=TaskKind.TESTS,
                output_path="tests/test_api.py",
                prompt_builder=lambda: tests_prompt(spec),
                metadata={"endpoint_count": len(spec.endpoints)},
            )
        )

    return tasks
